on:
  push:
    branches:
      - master

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"
      - name: deps
        run: sudo apt-get update && sudo apt-get install curl build-essential git -y
      - run: cd cmd && GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o vault-backup
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: v.0.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cmd/vault-backup
          asset_name: vault-backup.linux-amd64
          asset_content_type: application/octet-stream
  docker:
    runs-on: ubuntu-latest
    needs: [artifact]
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install curl build-essential git -y
      - run: docker build -t skydev/vault-backup:latest .
      - run: docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker push skydev/vault-backup:latest